name: "mopo"

freq_train_model: ${task.freq_train_model}
real_data_ratio: 0.0

sac_samples_action: true
random_initial_explore: false
num_eval_episodes: 5

dataset_size: 1000000
penalty_coeff: ${task.penalty_coeff}

# --------------------------------------------
#          SAC Agent configuration
# --------------------------------------------
agent:
  _target_: cmrl.third_party.pytorch_sac.sac.SAC
  num_inputs: ???
  action_space:
    _target_: gym.spaces.Box
    low: ???
    high: ???
    shape: ???
  args:
    gamma: ${task.sac_gamma}
    tau: ${task.sac_tau}
    alpha: ${task.sac_alpha}
    policy: ${task.sac_policy}
    target_update_interval: ${task.sac_target_update_interval}
    automatic_entropy_tuning: ${task.sac_automatic_entropy_tuning}
    target_entropy: ${task.sac_target_entropy}
    hidden_size: ${task.sac_hidden_size}
    device: ${device}
    lr: ${task.sac_lr}