name: "on_dyna"

freq_train_model: ${task.freq_train_model}
real_data_ratio: 0.0

sac_samples_action: true
initial_exploration_steps: 5000
random_initial_explore: true
num_eval_episodes: 5

# --------------------------------------------
#          SAC Agent configuration
# --------------------------------------------
agent:
  _target_: stable_baselines3.sac.SAC
  policy: "MlpPolicy"
  env:
    _target_: cmrl.models.fake_env.VecFakeEnv
    num_envs: 16
    action_space:
      _target_: gym.spaces.Box
      low: ???
      high: ???
      shape: ???
    observation_space:
      _target_: gym.spaces.Box
      low: ???
      high: ???
      shape: ???
  learning_starts: 100
  batch_size: 256
  tau: 0.005
  gamma: 0.99
  ent_coef: "auto"
  target_entropy: "auto"
  verbose: 0
  seed: ${seed}
  device: ${device}
