name: "plain_reward"
learn: false

mech:
  _partial_: true
  _recursive_: false
  _target_: cmrl.models.causal_mech.PlainMech
  name: ${transition.name}
  # base causal-mech params
  input_variables: ???
  output_variables: ???
  node_dim: 20
  variable_encoders: ???
  variable_decoders: ???
  # network params
  deterministic: false
  hidden_dims: [ 200, 200, 200, 200 ]
  ensemble_num: 7
  elite_num: 5
  use_bias: true
  activation_fn_cfg:
    _target_: torch.nn.SiLU
  # forward method
  residual: true
  multi_step: "none"
  # trainer
  optim_lr: 1e-4
  optim_weight_decay: 1e-5
  optim_eps: 1e-8
  optim_encoder: true
  # logger
  logger: ???
  # others
  device: ${device}
